# Generated by Django 5.2.12 on 2026-03-19 23:42

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REFERRED', 'Referred'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('referral_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['case_id'], name='idx_audit_log_case_id'), models.Index(fields=['performed_at'], name='idx_audit_log_performed_at'), models.Index(fields=['table_name', 'record_id'], name='idx_audit_log_record')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('doc_type', models.CharField(choices=[('DEED', 'Deed'), ('UCC', 'UCC'), ('IRS_990', 'IRS 990'), ('AUDITOR', 'Auditor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('source_url', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NOT_NEEDED', 'Not needed')], default='PENDING', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='investigations.case')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('narrative', models.TextField()),
                ('orc_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='findings', to='investigations.case')),
            ],
            options={
                'db_table': 'findings',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('CHARITY', 'Charity'), ('LLC', 'LLC'), ('CORPORATION', 'Corporation'), ('GOVERNMENT', 'Government'), ('CIC', 'CIC'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('ein', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_state', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISSOLVED', 'Dissolved'), ('REVOKED', 'Revoked'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organizations', to='investigations.case')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrgDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('context_note', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='investigations.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='investigations.organization')),
            ],
            options={
                'db_table': 'org_document',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('role_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='persons', to='investigations.case')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='FinancialInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('UCC_FILING', 'UCC filing'), ('LIEN', 'Lien'), ('MORTGAGE', 'Mortgage'), ('LOAN', 'Loan'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('filing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('secured_party_id', models.UUIDField(blank=True, null=True)),
                ('debtor_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('anomaly_flags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_instruments', to='investigations.case')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_instruments', to='investigations.person')),
            ],
            options={
                'db_table': 'financial_instruments',
            },
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('context_note', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='investigations.document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='investigations.person')),
            ],
            options={
                'db_table': 'person_document',
            },
        ),
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='investigations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='investigations.person')),
            ],
            options={
                'db_table': 'person_org',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valuation_delta', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('purchase_price'), '-', models.F('assessed_value')), null=True, output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='properties', to='investigations.case')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('buyer_id', models.UUIDField(blank=True, null=True)),
                ('seller_id', models.UUIDField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_transactions', to='investigations.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investigations.property')),
            ],
            options={
                'db_table': 'property_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='idx_documents_case_id'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['case'], name='idx_findings_case_id'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['case'], name='idx_organizations_case_id'),
        ),
        migrations.AddIndex(
            model_name='orgdocument',
            index=models.Index(fields=['document'], name='idx_org_document_doc'),
        ),
        migrations.AddConstraint(
            model_name='orgdocument',
            constraint=models.UniqueConstraint(fields=('org', 'document'), name='uniq_org_document_pair'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['case'], name='idx_persons_case_id'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['case'], name='idx_fin_instr_case_id'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['signer'], name='idx_fin_instr_signer'),
        ),
        migrations.AddIndex(
            model_name='persondocument',
            index=models.Index(fields=['document'], name='idx_person_document_doc'),
        ),
        migrations.AddConstraint(
            model_name='persondocument',
            constraint=models.UniqueConstraint(fields=('person', 'document'), name='uniq_person_document_pair'),
        ),
        migrations.AddConstraint(
            model_name='personorganization',
            constraint=models.UniqueConstraint(fields=('person', 'org', 'role'), name='uniq_person_org_role'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['case'], name='idx_properties_case_id'),
        ),
        migrations.AddIndex(
            model_name='propertytransaction',
            index=models.Index(fields=['property'], name='idx_prop_tx_property'),
        ),
    ]
