# Generated by Django 5.2.12 on 2026-03-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentReferral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_id', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.DateTimeField(blank=True, null=True)),
                ('contact_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Submitted', max_length=50)),
            ],
            options={
                'db_table': 'government_referrals',
            },
        ),
    ]
