# Generated by Django 5.2.12 on 2026-03-19 23:53

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_referral_timestamp_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentreferral',
            name='filing_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='governmentreferral',
            name='status',
            field=models.CharField(db_default=models.Value('Submitted'), default='Submitted', max_length=50),
        ),
    ]
