# Generated by Django 5.2.12 on 2026-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_alter_governmentreferral_filing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_subtype',
            field=models.CharField(blank=True, default='', help_text='Optional free-text subtype for additional classification detail.', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='True for outputs produced by Catalyst (memos, reports). False for source documents ingested as evidence.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DEED', 'Deed'), ('PARCEL_RECORD', 'Parcel Record'), ('RECORDER_INSTRUMENT', 'Recorder Instrument'), ('MORTGAGE', 'Mortgage'), ('LIEN', 'Lien'), ('UCC', 'UCC Filing'), ('IRS_990', 'IRS Form 990'), ('IRS_990T', 'IRS Form 990-T'), ('SOS_FILING', 'SOS Filing'), ('COURT_FILING', 'Court Filing'), ('DEATH_RECORD', 'Death Record / Obituary'), ('SUSPECTED_FORGERY', 'Suspected Forgery'), ('WEB_ARCHIVE', 'Web Archive / Screenshot'), ('REFERRAL_MEMO', 'Referral / Complaint Memo'), ('AUDITOR', 'Auditor'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
