# Generated by Django 5.2.12 on 2026-03-27 02:22

import django.contrib.postgres.fields
from django.db import migrations, models


def backfill_person_notes(apps, schema_editor):
    Person = apps.get_model('investigations', 'Person')
    Person.objects.filter(notes__isnull=True).update(notes='')


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0005_document_doc_subtype_document_is_generated_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_person_notes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='role_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BOARD_MEMBER', 'Board member'), ('OFFICER', 'Officer'), ('REGISTERED_AGENT', 'Registered agent'), ('INCORPORATOR', 'Incorporator'), ('SECURED_PARTY', 'Secured party'), (
                'DEBTOR', 'Debtor'), ('SIGNER', 'Signer'), ('GRANTOR', 'Grantor'), ('GRANTEE', 'Grantee'), ('DECEASED', 'Deceased'), ('SUBJECT_OF_INVESTIGATION', 'Subject of investigation'), ('WITNESS', 'Witness')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
