# Generated by Django 5.2.12 on 2026-03-28 01:06

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0006_alter_person_notes_alter_person_role_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='orc_reference',
        ),
        migrations.AddField(
            model_name='finding',
            name='confidence',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROBABLE', 'Probable'), ('POSSIBLE', 'Possible')], default='POSSIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='legal_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="ORC sections and federal statutes (e.g. '18 U.S.C. § 1343').", size=None),
        ),
        migrations.AddField(
            model_name='finding',
            name='signal_rule_id',
            field=models.CharField(blank=True, default='', help_text='Originating signal rule (e.g. SR-001) if applicable.', max_length=10),
        ),
        migrations.AddField(
            model_name='finding',
            name='signal_type',
            field=models.CharField(blank=True, default='', help_text='Category of anomaly: VALUATION_ANOMALY, DATE_ANOMALY, DISCLOSURE_OMISSION, CONCENTRATION_FLAG, IDENTITY_FRAUD, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('INCLUDED_IN_MEMO', 'Included in memo'), ('EXCLUDED', 'Excluded'), ('REFERRED', 'Referred')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DEED', 'Deed'), ('PARCEL_RECORD', 'Parcel Record'), ('RECORDER_INSTRUMENT', 'Recorder Instrument'), ('MORTGAGE', 'Mortgage'), ('LIEN', 'Lien'), ('UCC', 'UCC Filing'), ('IRS_990', 'IRS Form 990'), ('IRS_990T', 'IRS Form 990-T'), ('BUILDING_PERMIT', 'Building Permit'), ('CORP_FILING', 'Corporate Filing'), ('SOS_FILING', 'SOS Filing'), ('COURT_FILING', 'Court Filing'), ('DEATH_RECORD', 'Death Record / Obituary'), ('SUSPECTED_FORGERY', 'Suspected Forgery'), ('WEB_ARCHIVE', 'Web Archive / Screenshot'), ('REFERRAL_MEMO', 'Referral / Complaint Memo'), ('AUDITOR', 'Auditor'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='role_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BOARD_MEMBER', 'Board member'), ('OFFICER', 'Officer'), ('REGISTERED_AGENT', 'Registered agent'), ('INCORPORATOR', 'Incorporator'), ('SECURED_PARTY', 'Secured party'), ('DEBTOR', 'Debtor'), ('SIGNER', 'Signer'), ('GRANTOR', 'Grantor'), ('GRANTEE', 'Grantee'), ('DECEASED', 'Deceased'), ('ATTORNEY', 'Attorney'), ('NOTARY', 'Notary'), ('TRUSTEE', 'Trustee'), ('CONTRACTOR', 'Contractor'), ('FAMILY_MEMBER', 'Family member'), ('SUBJECT_OF_INVESTIGATION', 'Subject of investigation'), ('WITNESS', 'Witness')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('trigger_entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('investigator_note', models.TextField(blank=True, help_text='Required when dismissed — rationale for dismissal.', null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signals', to='investigations.case')),
                ('trigger_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='investigations.document')),
            ],
            options={
                'db_table': 'signals',
            },
        ),
        migrations.CreateModel(
            name='EntitySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField()),
                ('entity_type', models.CharField(max_length=50)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='investigations.signal')),
            ],
            options={
                'db_table': 'entity_signal',
            },
        ),
        migrations.CreateModel(
            name='FindingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('context_note', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='investigations.document')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='investigations.finding')),
            ],
            options={
                'db_table': 'finding_document',
                'indexes': [models.Index(fields=['document'], name='idx_finding_document_doc')],
                'constraints': [models.UniqueConstraint(fields=('finding', 'document'), name='uniq_finding_document_pair')],
            },
        ),
        migrations.CreateModel(
            name='FindingEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField()),
                ('entity_type', models.CharField(max_length=50)),
                ('context_note', models.TextField(blank=True, null=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='investigations.finding')),
            ],
            options={
                'db_table': 'finding_entity',
                'indexes': [models.Index(fields=['finding'], name='idx_finding_entity_finding')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['case'], name='idx_signals_case_id'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['rule_id'], name='idx_signals_rule_id'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['status'], name='idx_signals_status'),
        ),
        migrations.AddIndex(
            model_name='entitysignal',
            index=models.Index(fields=['signal'], name='idx_entity_signal_signal'),
        ),
        migrations.AddConstraint(
            model_name='entitysignal',
            constraint=models.UniqueConstraint(fields=('signal', 'entity_id', 'entity_type'), name='uniq_entity_signal'),
        ),
    ]
