# Generated by Django 5.2.12 on 2026-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0007_signal_entitysignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formation_date',
            field=models.DateField(blank=True, help_text='Date the entity was legally formed per Secretary of State records. Used for SR-002 signal detection.', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='detected_summary',
            field=models.TextField(blank=True, default='', help_text='Machine-generated explanation of what triggered this signal.'),
        ),
    ]
