# Generated by Django 5.2.12 on 2026-03-30 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0010_documenttype_occ_cic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentreferral',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('CLOSED', 'Closed')], db_default=models.Value('DRAFT'), default='DRAFT', max_length=50),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('DECEASED_SIGNER', 'Deceased signer'), ('DATE_IMPOSSIBILITY', 'Date impossibility'), ('MISSING_REQUIRED_FIELDS', 'Missing required fields'), ('METADATA_MISMATCH', 'Metadata mismatch'), ('HASH_CHANGE', 'Hash change on re-intake'), ('VALUATION_DELTA', 'Property valuation delta'), ('SELF_DEALING', 'Self-dealing indicator'), ('UCC_LOOP', 'UCC lien loop'), ('PROCUREMENT_BYPASS', 'Procurement bypass'), ('REVENUE_ANOMALY', '990 revenue anomaly'), ('PHANTOM_OFFICER', 'Phantom officer'), ('NAME_RECONCILIATION', 'Name reconciliation'), ('TIMELINE_COMPRESSION', 'Timeline compression'), ('CHARTER_CONFLICT', 'Charter status conflict'), ('ADDRESS_NEXUS', 'Address nexus'), ('ASSET_DISCREPANCY', '990 vs deed asset discrepancy')], max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('CONFIRMED', 'Confirmed — valid signal'), ('DISMISSED', 'Dismissed — false positive'), ('ESCALATED', 'Escalated to finding')], default='OPEN', max_length=20)),
                ('detection_method', models.CharField(choices=[('SYSTEM_AUTO', 'Detected automatically by system'), ('INVESTIGATOR_MANUAL', 'Flagged manually by investigator')], default='SYSTEM_AUTO', max_length=30)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('investigator_note', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='investigations.case')),
                ('financial_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='investigations.financialinstrument')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='investigations.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='investigations.person')),
                ('primary_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections_as_primary', to='investigations.document')),
                ('property_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='investigations.property')),
                ('secondary_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections_as_secondary', to='investigations.document')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='investigati_case_id_21f160_idx'), models.Index(fields=['case', 'severity'], name='investigati_case_id_836eb6_idx'), models.Index(fields=['signal_type'], name='investigati_signal__dc0059_idx')],
            },
        ),
    ]
