# Generated by Django 5.2.12 on 2026-03-30 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0011_alter_governmentreferral_status_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='detection',
            field=models.ForeignKey(blank=True, help_text='The detection that was escalated to produce this finding, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='investigations.detection'),
        ),
    ]
