# Generated by Django 5.2.12 on 2026-03-31 15:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0012_finding_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigatorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(help_text='The type of entity this note is attached to: case, document, signal, detection, person, organization, property, financial_instrument.', max_length=50)),
                ('target_id', models.UUIDField(help_text='The primary key of the target record this note is attached to.')),
                ('content', models.TextField()),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator_notes', to='investigations.case')),
            ],
            options={
                'db_table': 'investigator_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='idx_inv_notes_case'), models.Index(fields=['target_type', 'target_id'], name='idx_inv_notes_target')],
            },
        ),
    ]
