# Generated by Django 5.2.12 on 2026-03-31 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0013_investigatornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='SSN, ITIN, or PTIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='role_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BOARD_MEMBER', 'Board member'), ('OFFICER', 'Officer'), ('REGISTERED_AGENT', 'Registered agent'), ('INCORPORATOR', 'Incorporator'), ('SECURED_PARTY', 'Secured party'), ('DEBTOR', 'Debtor'), ('SIGNER', 'Signer'), ('GRANTOR', 'Grantor'), ('GRANTEE', 'Grantee'), ('DECEASED', 'Deceased'), ('ATTORNEY', 'Attorney'), ('NOTARY', 'Notary'), ('TRUSTEE', 'Trustee'), ('TAX_PREPARER', 'Tax preparer'), ('CONTRACTOR', 'Contractor'), ('FAMILY_MEMBER', 'Family member'), ('SUBJECT_OF_INVESTIGATION', 'Subject of investigation'), ('WITNESS', 'Witness')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
