# Generated by Django 5.2.12 on 2026-03-31 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0014_person_org_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ein', models.CharField(blank=True, default='', max_length=20)),
                ('tax_year', models.IntegerField()),
                ('form_type', models.CharField(default='990', max_length=20)),
                ('total_contributions', models.BigIntegerField(blank=True, null=True)),
                ('program_service_revenue', models.BigIntegerField(blank=True, null=True)),
                ('investment_income', models.BigIntegerField(blank=True, null=True)),
                ('other_revenue', models.BigIntegerField(blank=True, null=True)),
                ('total_revenue', models.BigIntegerField(blank=True, null=True)),
                ('grants_paid', models.BigIntegerField(blank=True, null=True)),
                ('salaries_and_compensation', models.BigIntegerField(blank=True, null=True)),
                ('professional_fundraising', models.BigIntegerField(blank=True, null=True)),
                ('other_expenses', models.BigIntegerField(blank=True, null=True)),
                ('total_expenses', models.BigIntegerField(blank=True, null=True)),
                ('revenue_less_expenses', models.BigIntegerField(blank=True, null=True)),
                ('total_assets_boy', models.BigIntegerField(blank=True, null=True)),
                ('total_assets_eoy', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities_boy', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities_eoy', models.BigIntegerField(blank=True, null=True)),
                ('net_assets_boy', models.BigIntegerField(blank=True, null=True)),
                ('net_assets_eoy', models.BigIntegerField(blank=True, null=True)),
                ('officer_compensation_total', models.BigIntegerField(blank=True, null=True)),
                ('num_employees', models.IntegerField(blank=True, null=True)),
                ('num_voting_members', models.IntegerField(blank=True, null=True)),
                ('num_independent_members', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='EXTRACTED', help_text='EXTRACTED (from document OCR), PROPUBLICA (API), MANUAL', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0–1.0 extraction confidence')),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_snapshots', to='investigations.case')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='investigations.document')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_snapshots', to='investigations.organization')),
            ],
            options={
                'db_table': 'financial_snapshots',
                'ordering': ['-tax_year'],
                'indexes': [models.Index(fields=['case'], name='idx_fin_snapshot_case'), models.Index(fields=['tax_year'], name='idx_fin_snapshot_year')],
                'constraints': [models.UniqueConstraint(fields=('document', 'tax_year'), name='uniq_financial_snapshot_doc_year')],
            },
        ),
    ]
