# Generated by Django 5.2.12 on 2026-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0015_financial_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes at time of operation, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sha256_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the document involved, if applicable.', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(default=True, help_text='False if the operation failed. Failure details go in notes.'),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_notes',
            field=models.TextField(blank=True, default='', help_text='Details about any extraction failures (which steps failed and why).'),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial — some steps failed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped — no text available')], default='PENDING', help_text='Status of entity extraction and signal detection pipeline.', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_INGESTED', 'Document ingested'), ('DOCUMENT_SCRUBBED', 'Document metadata scrubbed'), ('DOCUMENT_HASHED', 'Document hash computed'), ('DOCUMENT_HASH_VERIFIED', 'Document hash re-verified'), ('DOCUMENT_HASH_MISMATCH', 'Document hash mismatch detected'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_OCR_COMPLETED', 'Document OCR completed'), ('DOCUMENT_OCR_FAILED', 'Document OCR failed'), ('RECORD_CREATED', 'Record created'), ('RECORD_UPDATED', 'Record updated'), ('RECORD_DELETED', 'Record deleted'), ('SIGNAL_DETECTED', 'Signal detected'), ('SIGNAL_CONFIRMED', 'Signal confirmed'), ('SIGNAL_DISMISSED', 'Signal dismissed'), ('SIGNAL_ESCALATED', 'Signal escalated to finding'), ('FINDING_CREATED', 'Finding created'), ('FINDING_UPDATED', 'Finding updated'), ('FINDING_INCLUDED', 'Finding included in memo'), ('REFERRAL_CREATED', 'Referral created'), ('REFERRAL_SUBMITTED', 'Referral submitted'), ('REFERRAL_STATUS_CHANGED', 'Referral status changed'), ('INTAKE_REJECTED_SIZE', 'File rejected — exceeds size limit'), ('INTAKE_REJECTED_TYPE', 'File rejected — invalid MIME type'), ('INTAKE_REJECTED_CORRUPT', 'File rejected — corrupted or unreadable'), ('HASH_VERIFICATION_BATCH', 'Batch hash verification completed')], help_text='Constrained action type — use AuditAction enum values only.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='idx_audit_log_action'),
        ),
    ]
