# Generated by Django 5.2.12 on 2026-04-03 03:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0018_document_ingestion_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.CharField(help_text='Address exactly as it appeared on the source document.', max_length=500)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('address_type', models.CharField(choices=[('MAILING', 'Mailing address'), ('REGISTERED', 'Registered agent address'), ('PROPERTY', 'Property address'), ('BUSINESS', 'Business / operating address'), ('RESIDENCE', 'Residential address'), ('FILING', 'Address on filing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('first_seen_date', models.DateField(blank=True, help_text='Earliest document date where this address appeared.', null=True)),
                ('last_seen_date', models.DateField(blank=True, help_text='Most recent document date where this address appeared.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='OrgAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_role', models.CharField(choices=[('MAILING', 'Mailing address'), ('REGISTERED', 'Registered agent address'), ('PROPERTY', 'Property address'), ('BUSINESS', 'Business / operating address'), ('RESIDENCE', 'Residential address'), ('FILING', 'Address on filing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org_address',
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_role', models.CharField(choices=[('MAILING', 'Mailing address'), ('REGISTERED', 'Registered agent address'), ('PROPERTY', 'Property address'), ('BUSINESS', 'Business / operating address'), ('RESIDENCE', 'Residential address'), ('FILING', 'Address on filing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_address',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('FAMILY', 'Family member'), ('SPOUSE', 'Spouse'), ('PARENT_CHILD', 'Parent / Child'), ('SIBLING', 'Sibling'), ('BUSINESS_PARTNER', 'Business partner'), ('CO_OFFICER', 'Co-officer in organization'), ('SOCIAL_CONNECTION', 'Social media connection'), ('ATTORNEY_CLIENT', 'Attorney / Client'), ('EMPLOYER_EMPLOYEE', 'Employer / Employee'), ('OTHER', 'Other')], max_length=30)),
                ('source', models.CharField(choices=[('DOCUMENT', 'Extracted from document'), ('SOS_FILING', 'Secretary of State filing'), ('SOCIAL_MEDIA', 'Social media (Facebook, etc.)'), ('OBITUARY', 'Obituary'), ('PUBLIC_RECORD', 'Public record'), ('INVESTIGATOR', 'Investigator observation')], default='INVESTIGATOR', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0–1.0. Lower for inferred relationships.')),
                ('notes', models.TextField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_name', models.CharField(blank=True, default='', help_text='Name as it appears on the social platform (before linking to a Person).', max_length=255)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter / X'), ('INSTAGRAM', 'Instagram'), ('OTHER', 'Other')], max_length=20)),
                ('connection_type', models.CharField(choices=[('FRIEND', 'Friend / connection'), ('FOLLOWER', 'Follower'), ('GROUP_MEMBER', 'Same group member'), ('TAGGED', 'Tagged in post'), ('OTHER', 'Other')], default='FRIEND', max_length=20)),
                ('profile_url', models.URLField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'social_media_connections',
            },
        ),
        migrations.CreateModel(
            name='TransactionChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_type', models.CharField(choices=[('INSIDER_SWAP', 'Insider swap (buy → related-party transfer)'), ('FLIP', 'Property flip (buy → quick resale)'), ('CIRCULAR', 'Circular transfer (A→B→C→A)'), ('LAYERED', 'Layered transactions (obscuring beneficial owner)'), ('OTHER', 'Other pattern')], max_length=20)),
                ('status', models.CharField(choices=[('SUSPECTED', 'System-detected, awaiting review'), ('CONFIRMED', 'Investigator-confirmed pattern'), ('DISMISSED', 'False positive'), ('ESCALATED', 'Escalated to finding')], default='SUSPECTED', max_length=20)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'ExampleOwner → Example Charity swap (SR-068)'", max_length=255)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all transaction prices in the chain.', max_digits=14, null=True)),
                ('time_span_days', models.IntegerField(blank=True, help_text='Days between first and last transaction in chain.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transaction_chains',
            },
        ),
        migrations.CreateModel(
            name='TransactionChainLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order in chain: 1 = first transaction, 2 = second, etc.')),
                ('role_description', models.CharField(blank=True, default='', help_text="E.g. 'Charity purchases from ExampleOwner' or 'Insider receives property'", max_length=255)),
            ],
            options={
                'db_table': 'transaction_chain_links',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='amendment_type',
            field=models.CharField(blank=True, default='', help_text='INITIAL, AMENDMENT, CONTINUATION, TERMINATION, ASSIGNMENT.', max_length=50),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='collateral_description',
            field=models.TextField(blank=True, default='', help_text="UCC collateral description (e.g. 'all farm equipment, livestock')."),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='continuation_date',
            field=models.DateField(blank=True, help_text='Date a continuation statement was filed to extend the lien.', null=True),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='filing_state',
            field=models.CharField(blank=True, default='', help_text="State where the UCC was filed (e.g. 'OH').", max_length=2),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='is_blanket_lien',
            field=models.BooleanField(default=False, help_text="True if filing covers 'all assets' or equivalent blanket language."),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='lapse_date',
            field=models.DateField(blank=True, help_text='Date the UCC filing lapses (typically 5 years from filing).', null=True),
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='parent_filing',
            field=models.ForeignKey(blank=True, help_text='For amendments/continuations, links to the original filing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='investigations.financialinstrument'),
        ),
        migrations.AddField(
            model_name='property',
            name='acreage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Property size in acres, if known.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='current_owner_name',
            field=models.CharField(blank=True, default='', help_text='Owner per most recent auditor/parcel record.', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, default='', help_text='E.g. RESIDENTIAL, COMMERCIAL, AGRICULTURAL, VACANT_LAND.', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, default='OH', help_text='State abbreviation. Defaults to OH for Ohio cases.', max_length=2),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='buyer_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized buyer name for quick display.', max_length=255),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], default='', help_text='Whether the buyer is a Person or Organization.', max_length=20),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='instrument_number',
            field=models.CharField(blank=True, default='', help_text='Recorder instrument number from county records.', max_length=100),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='seller_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized seller name for quick display.', max_length=255),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], default='', help_text='Whether the seller is a Person or Organization.', max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='signal_type',
            field=models.CharField(choices=[('DECEASED_SIGNER', 'Deceased signer'), ('DATE_IMPOSSIBILITY', 'Date impossibility'), ('MISSING_REQUIRED_FIELDS', 'Missing required fields'), ('METADATA_MISMATCH', 'Metadata mismatch'), ('HASH_CHANGE', 'Hash change on re-intake'), ('VALUATION_DELTA', 'Property valuation delta'), ('MULTI_COUNTY_CLUSTER', 'Properties across multiple counties'), ('SELF_DEALING', 'Self-dealing indicator'), ('INSIDER_SWAP', 'Insider swap pattern'), ('RELATED_PARTY_TX', 'Related-party transaction'), ('UCC_LOOP', 'UCC lien loop'), ('UCC_BLANKET_LIEN', 'UCC blanket lien'), ('UCC_AMENDMENT_CHAIN', 'Suspicious UCC amendment chain'), ('PROCUREMENT_BYPASS', 'Procurement bypass'), ('REVENUE_ANOMALY', '990 revenue anomaly'), ('EXPENSE_RATIO', 'Abnormal expense ratio'), ('ASSET_DISCREPANCY', '990 vs deed asset discrepancy'), ('PHANTOM_OFFICER', 'Phantom officer'), ('NAME_RECONCILIATION', 'Name reconciliation'), ('TIMELINE_COMPRESSION', 'Timeline compression'), ('CHARTER_CONFLICT', 'Charter status conflict'), ('ADDRESS_NEXUS', 'Address nexus'), ('ENTITY_PROLIFERATION', 'Rapid entity proliferation'), ('FAMILY_NETWORK', 'Dense family network in governance'), ('SOCIAL_CLUSTER', 'Social media connection cluster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('CHARITY', 'Charity / 501(c)(3)'), ('LLC', 'LLC'), ('CORPORATION', 'Corporation'), ('LLP', 'Limited Liability Partnership'), ('PARTNERSHIP', 'General Partnership'), ('SOLE_PROP', 'Sole Proprietorship'), ('LAND_TRUST', 'Land Trust'), ('FARM_LLC', 'Farm / Agricultural LLC'), ('HMAIN', 'Hmain Company'), ('FILM_PROD', 'Film / Media Production'), ('GOVERNMENT', 'Government'), ('CIC', 'CIC'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['is_blanket_lien'], name='idx_fin_instr_blanket'),
        ),
        migrations.AddIndex(
            model_name='propertytransaction',
            index=models.Index(fields=['transaction_date'], name='idx_prop_tx_date'),
        ),
        migrations.AddIndex(
            model_name='propertytransaction',
            index=models.Index(fields=['buyer_id'], name='idx_prop_tx_buyer'),
        ),
        migrations.AddIndex(
            model_name='propertytransaction',
            index=models.Index(fields=['seller_id'], name='idx_prop_tx_seller'),
        ),
        migrations.AddField(
            model_name='address',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='addresses', to='investigations.case'),
        ),
        migrations.AddField(
            model_name='address',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Document where this address was first extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses_sourced', to='investigations.document'),
        ),
        migrations.AddField(
            model_name='property',
            name='normalized_address',
            field=models.ForeignKey(blank=True, help_text='Link to normalized Address record for nexus detection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='investigations.address'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county'], name='idx_properties_county'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'county'], name='idx_properties_state_county'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_addresses', to='investigations.address'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_links', to='investigations.organization'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.document'),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_addresses', to='investigations.address'),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_links', to='investigations.person'),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.document'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='relationships', to='investigations.case'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='investigations.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='investigations.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_evidence', to='investigations.document'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='social_connections', to='investigations.case'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='connected_person',
            field=models.ForeignKey(blank=True, help_text='If the connected party is already a Person in this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_connected_by', to='investigations.person'),
        ),
        migrations.AddField(
            model_name='socialmediaconnection',
            name='person',
            field=models.ForeignKey(help_text='The case person whose social profile was examined.', on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='investigations.person'),
        ),
        migrations.AddField(
            model_name='transactionchain',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_chains', to='investigations.case'),
        ),
        migrations.AddField(
            model_name='transactionchain',
            name='signal',
            field=models.ForeignKey(blank=True, help_text='The Signal record that triggered creation of this chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_chains', to='investigations.signal'),
        ),
        migrations.AddField(
            model_name='transactionchainlink',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='investigations.transactionchain'),
        ),
        migrations.AddField(
            model_name='transactionchainlink',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_links', to='investigations.propertytransaction'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['case'], name='idx_addresses_case'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street', 'city', 'state'], name='idx_addresses_location'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['county'], name='idx_addresses_county'),
        ),
        migrations.AddConstraint(
            model_name='orgaddress',
            constraint=models.UniqueConstraint(fields=('org', 'address', 'address_role'), name='uniq_org_address_role'),
        ),
        migrations.AddConstraint(
            model_name='personaddress',
            constraint=models.UniqueConstraint(fields=('person', 'address', 'address_role'), name='uniq_person_address_role'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['case'], name='idx_relationships_case'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['relationship_type'], name='idx_relationships_type'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('person_a', 'person_b', 'relationship_type'), name='uniq_relationship_pair_type'),
        ),
        migrations.AddIndex(
            model_name='socialmediaconnection',
            index=models.Index(fields=['case'], name='idx_social_conn_case'),
        ),
        migrations.AddIndex(
            model_name='socialmediaconnection',
            index=models.Index(fields=['person'], name='idx_social_conn_person'),
        ),
        migrations.AddIndex(
            model_name='socialmediaconnection',
            index=models.Index(fields=['platform'], name='idx_social_conn_platform'),
        ),
        migrations.AddIndex(
            model_name='transactionchain',
            index=models.Index(fields=['case'], name='idx_tx_chains_case'),
        ),
        migrations.AddIndex(
            model_name='transactionchain',
            index=models.Index(fields=['chain_type'], name='idx_tx_chains_type'),
        ),
        migrations.AddIndex(
            model_name='transactionchain',
            index=models.Index(fields=['status'], name='idx_tx_chains_status'),
        ),
        migrations.AddConstraint(
            model_name='transactionchainlink',
            constraint=models.UniqueConstraint(fields=('chain', 'transaction'), name='uniq_chain_transaction'),
        ),
        migrations.AddConstraint(
            model_name='transactionchainlink',
            constraint=models.UniqueConstraint(fields=('chain', 'sequence_number'), name='uniq_chain_sequence'),
        ),
    ]
