# Generated by Django 5.2.13 on 2026-04-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0019_address_orgaddress_personaddress_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='case',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='financial_instrument',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='person',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='primary_document',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='property_record',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='secondary_document',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='entitysignal',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='case',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='trigger_doc',
        ),
        migrations.RemoveField(
            model_name='transactionchain',
            name='signal',
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='finding',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='signal_rule_id',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='signal_type',
        ),
        migrations.AddField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Machine-generated explanation of what triggered this finding.'),
        ),
        migrations.AddField(
            model_name='finding',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Structured evidence data captured at detection time.'),
        ),
        migrations.AddField(
            model_name='finding',
            name='evidence_weight',
            field=models.CharField(choices=[('SPECULATIVE', 'Speculative — pattern matched only'), ('DIRECTIONAL', 'Directional — suggestive but unproven'), ('DOCUMENTED', 'Documented — supporting docs on file'), ('TRACED', 'Traced — full citation chain to source')], default='SPECULATIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='investigator_note',
            field=models.TextField(blank=True, default='', help_text='Investigator notes — required when dismissing.'),
        ),
        migrations.AddField(
            model_name='finding',
            name='rule_id',
            field=models.CharField(blank=True, default='', help_text='Signal rule that generated this (e.g. SR-003). Blank for manual findings.', max_length=10),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Auto-detected by signal rules'), ('MANUAL', 'Manually created by investigator')], default='AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='trigger_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_triggered', to='investigations.document'),
        ),
        migrations.AddField(
            model_name='finding',
            name='trigger_entity_id',
            field=models.UUIDField(blank=True, help_text='UUID of the entity this finding is primarily about.', null=True),
        ),
        migrations.AddField(
            model_name='transactionchain',
            name='finding',
            field=models.ForeignKey(blank=True, help_text='The Finding record that triggered creation of this chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_chains', to='investigations.finding'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='narrative',
            field=models.TextField(blank=True, default='', help_text='Investigator-written narrative for the referral package.'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('NEW', 'New — auto-detected, not yet reviewed'), ('NEEDS_EVIDENCE', 'Needs evidence'), ('DISMISSED', 'Dismissed — false positive'), ('CONFIRMED', 'Confirmed — included in referral')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='findingdocument',
            name='context_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='findingdocument',
            name='page_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='findingentity',
            name='context_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='investigatornote',
            name='target_type',
            field=models.CharField(help_text='The type of entity this note is attached to: case, document, finding, person, organization, property, financial_instrument.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rule_id'], name='idx_findings_rule_id'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status'], name='idx_findings_status'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['case', 'status'], name='idx_findings_case_status'),
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='EntitySignal',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
