# Generated by Django 5.2.13 on 2026-04-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0020_remove_detection_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaconnection',
            name='case',
        ),
        migrations.RemoveField(
            model_name='socialmediaconnection',
            name='connected_person',
        ),
        migrations.RemoveField(
            model_name='socialmediaconnection',
            name='person',
        ),
        migrations.DeleteModel(
            name='GovernmentReferral',
        ),
        migrations.DeleteModel(
            name='SocialMediaConnection',
        ),
    ]
