from django.urls import path

from . import views

urlpatterns = [
    path("api/csrf/", views.api_csrf_token, name="api_csrf_token"),
    path(
        "api/cases/",
        views.api_case_collection,
        name="api_case_collection",
    ),
    path(
        "api/signal-summary/",
        views.api_signal_summary,
        name="api_signal_summary",
    ),
    path("api/search/", views.api_search, name="api_search"),
    path(
        "api/entities/",
        views.api_entity_collection,
        name="api_entity_collection",
    ),
    path(
        "api/entities/<str:entity_type>/<uuid:entity_id>/",
        views.api_entity_detail,
        name="api_entity_detail",
    ),
    path(
        "api/activity-feed/",
        views.api_activity_feed,
        name="api_activity_feed",
    ),
    path(
        "api/cases/<uuid:pk>/",
        views.api_case_detail,
        name="api_case_detail",
    ),
    path(
        "api/cases/<uuid:pk>/export/",
        views.api_case_export,
        name="api_case_export",
    ),
    path(
        "api/cases/<uuid:pk>/documents/",
        views.api_case_document_collection,
        name="api_case_document_collection",
    ),
    path(
        "api/cases/<uuid:pk>/documents/bulk/",
        views.api_case_document_bulk_upload,
        name="api_case_document_bulk_upload",
    ),
    path(
        "api/cases/<uuid:pk>/documents/process-pending/",
        views.api_case_document_process_pending,
        name="api_case_document_process_pending",
    ),
    path(
        "api/cases/<uuid:pk>/fetch-990s/",
        views.api_case_fetch_990s,
        name="api_case_fetch_990s",
    ),
    path(
        "api/cases/<uuid:pk>/research/parcels/",
        views.api_research_parcels,
        name="api_research_parcels",
    ),
    path(
        "api/cases/<uuid:pk>/research/ohio-sos/",
        views.api_research_ohio_sos,
        name="api_research_ohio_sos",
    ),
    path(
        "api/cases/<uuid:pk>/research/ohio-aos/",
        views.api_research_ohio_aos,
        name="api_research_ohio_aos",
    ),
    path(
        "api/cases/<uuid:pk>/research/irs/",
        views.api_research_irs,
        name="api_research_irs",
    ),
    path(
        "api/cases/<uuid:pk>/research/recorder/",
        views.api_research_recorder,
        name="api_research_recorder",
    ),
    path(
        "api/cases/<uuid:pk>/research/add-to-case/",
        views.api_research_add_to_case,
        name="api_research_add_to_case",
    ),
    path(
        "api/jobs/<uuid:job_id>/",
        views.api_job_detail,
        name="api_job_detail",
    ),
    path(
        "api/cases/<uuid:pk>/jobs/",
        views.api_case_jobs,
        name="api_case_jobs",
    ),
    path(
        "api/cases/<uuid:pk>/documents/<uuid:document_id>/",
        views.api_case_document_detail,
        name="api_case_document_detail",
    ),
    path(
        "api/cases/<uuid:pk>/financials/",
        views.api_case_financials,
        name="api_case_financials",
    ),
    path(
        "api/cases/<uuid:pk>/findings/",
        views.api_case_finding_collection,
        name="api_case_finding_collection",
    ),
    path(
        "api/cases/<uuid:pk>/findings/<uuid:finding_id>/",
        views.api_case_finding_detail,
        name="api_case_finding_detail",
    ),
    path(
        "api/cases/<uuid:pk>/referral-pdf/",
        views.api_case_referral_pdf,
        name="api_case_referral_pdf",
    ),
    path(
        "api/cases/<uuid:pk>/notes/",
        views.api_case_note_collection,
        name="api_case_note_collection",
    ),
    path(
        "api/cases/<uuid:pk>/notes/<uuid:note_id>/",
        views.api_case_note_detail,
        name="api_case_note_detail",
    ),
    path(
        "api/cases/<uuid:pk>/reevaluate-findings/",
        views.api_case_reevaluate_findings,
        name="api_case_reevaluate_findings",
    ),
    path(
        "api/cases/<uuid:pk>/dashboard/",
        views.api_case_dashboard,
        name="api_case_dashboard",
    ),
    path(
        "api/cases/<uuid:pk>/coverage/",
        views.api_case_coverage,
        name="api_case_coverage",
    ),
    path(
        "api/cases/<uuid:pk>/graph/",
        views.api_case_graph,
        name="api_case_graph",
    ),
    # Admin endpoints (SOS CSV management)
    path(
        "api/admin/upload-sos-csv/",
        views.api_admin_upload_sos_csv,
        name="api_admin_upload_sos_csv",
    ),
    path(
        "api/admin/sos-csv-status/",
        views.api_admin_sos_csv_status,
        name="api_admin_sos_csv_status",
    ),
    # AI endpoints
    path(
        "api/cases/<uuid:pk>/ai/summarize/",
        views.api_ai_summarize,
        name="api_ai_summarize",
    ),
    path(
        "api/cases/<uuid:pk>/ai/connections/",
        views.api_ai_connections,
        name="api_ai_connections",
    ),
    path(
        "api/cases/<uuid:pk>/ai/narrative/",
        views.api_ai_narrative,
        name="api_ai_narrative",
    ),
    path(
        "api/cases/<uuid:pk>/ai/ask/",
        views.api_ai_ask,
        name="api_ai_ask",
    ),
    path(
        "api/cases/<uuid:pk>/ai/analyze-patterns/",
        views.api_ai_analyze_patterns,
        name="api_ai_analyze_patterns",
    ),
    path("", views.case_list, name="case_list"),
    path("cases/new/", views.case_create, name="case_create"),
    path(
        "cases/<uuid:pk>/",
        views.case_detail,
        name="case_detail",
    ),
    path(
        "documents/upload/",
        views.document_upload,
        name="document_upload",
    ),
]
